### ISSUE TITLE
Create and add environment file to the project

### ISSUE THREAD

**Issue by fatawesome** [fatawesome/Lib_Inno#6]
All information can be find in internet.

**Comment by BananaAndBread** [comment]
What do you mean?

**Comment by fatawesome** [comment]
http://lmgtfy.com/?q=environment.txt+django

**Comment by BananaAndBread** [comment]
![image](https://user-images.githubusercontent.com/32180157/36321534-2fc4237c-135b-11e8-9aa6-1d45acfec555.png)
 
There is no environment.txt there. Can you help Dasha find the file?
